# Generated by Django 2.0 on 2022-03-18 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chatusers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatusers',
            options={'ordering': ('timestamp',)},
        ),
    ]
